### PR TITLE
Czech translation improvement

### PR DESCRIPTION
**Pull request by ceskyDJ**
Hi, @sbs20,

I found a little mistake in my translation, so I've replaced it with a better translation.

There is one thing I need to ask you - what about other messages? Are they all informative messages (like something happened)? In this case 2 other translations are bad and needs to fix. I speak about:
```json
    "message:turn-documents": "Obrátit dokumenty",
    "message:preview-of-page": "Náhled strany"
```

Now its translated in these ways:
- `message:turn-documents` --> "Obrátit dokumenty" (Turn documents - imperative), not "Dokumenty byly obráceny" (Documents were turned - informative)
- `message:preview-of-page` --> "Náhled strany" (Page preview) - This is good translation if it's the heading of manual scanning window. Where is the true :D?

### CODE REVIEW

**Comment by sbs20** [comment]
Hello, and thank you.

Turn documents is imperative: you need to turn the documents over now

Preview of page is informative: below you will see a preview of the page you just scanned.

**Comment by ceskyDJ** [comment]
Ok, super! So, it should be ok and only the thing I've fixed in last commit was a mistake.

**Comment by ceskyDJ** [comment]
But... `message:turn-documents` is a message for the user of scanner that says "You must turn document now!", isn't it?

**Comment by sbs20** [comment]
Yes

**Comment by ceskyDJ** [comment]
Oh, ok. So, I'm sorry for making problems. This needs to be fixed, too. Better one is "Obraťte dokument". Is "documents" means as individual document?

**Comment by sbs20** [comment]
No problem! It's ambiguous. If a user is scanning a single piece of double sided paper, it's turn the page, if it's 20 pages, then turn the pages. I suppose if the pages could be a single document or more.

I'd suggest "pages" or "document". I haven't checked the English text!

**Comment by ceskyDJ** [comment]
So, it's for semi-automatic ADF scanner, right? You give it a pack of papers, it scans only one side of each list, so you need to turn it and give it back to scanner. Am I correct?

**Comment by sbs20** [comment]
Exactly right.

**Comment by ceskyDJ** [comment]
Ok, so "Obraťte skenované dokumenty" (Turn scanned documents) will be the best option, I think. So I'll update it.

**Pull request merged**
