### PR TITLE
Add ability to rename files in file list

### PR DESCRIPTION
**Pull request by Muehli25**
Hello,
the idea of this PR was to add an option to rename scanned documents, so i added an extra component which ist based on the data table from [Vuetify ](https://vuetifyjs.com/en/components/data-tables/), now it is possible to rename files.

### CODE REVIEW

**Comment by sbs20** [comment]
Thank you for this. I really like what you've done. It's a neater UI.

A few things though
* I don't really want two file components. It's twice as much to maintain
* The new page loses the ability to delete multiple files
* The new page has a delete confirmation, which I'm not a huge fan of
* The PR is against master (easily fixed)

Would you be up for:
* Removing the delete confirmation
* Adding multi-file delete
* Putting the changes into `Files.vue`
* Removing linting errors (see: https://stackoverflow.com/a/63309643/1229065)
* Issuing PR to `development`
* Bonus: enable sorting

If you can't, then I'll get around to it, but I'm a bit swamped with life at the moment, so don't have as much time to maintain!

**Comment by Muehli25** [comment]
Thanks for the input. I have a quiet busy week but i will do my best :)

**Comment by sbs20** [comment]
Take your time, I'm not going to be doing anything this big for at least 3 weeks! And thank you for contributing 😄

**Review by sbs20 — APPROVED** [review]
Awesome! Thank you so much - this is great.

**Comment by sbs20** [comment]
#325

**Pull request merged**
