### PR TITLE
Collation, inline filters, OCR fix

### LINKED ISSUE #98: Inline image filters e.g. black-and-white format
According to the (scanimage docs)[https://linux.die.net/man/1/scanimage] there is a `black-and-white` format. 

I believe this will mirror the black and white mode in my devices Windows software, but I am unable to select this from the UI. Is this trivial to add?

### PR DESCRIPTION
**Pull request by sbs20**
#98 
#123 
#124 
#125 
#126

### CODE REVIEW

**Comment by toxic0berliner** [comment]
Cool, thanks a lot! Will try to update and use this asap ;)

**Comment by sbs20** [comment]
No problem at all - thank you for filing issues!

**Comment by toxic0berliner** [comment]
Really cool software! I've decided to switch to using only this, I find using this in a browser is just perfect and way better than bloated softwares from printer manufacturers, and congrats on your reactivity and all the progress made since last time I checked it out only a year ago!
Is there a way to gift you a beer or something?

**Comment by sbs20** [comment]
Yeah, the scanner software from canon wouldn't even install for me! It's very kind of you to say. And very kind of you to offer a beer 🍺. I don't have a way of doing that right now, so just pay it forward somewhere and stay safe!

**Comment by sbs20** [comment]
If you don't mind I'm going to use your  quote anonymously on the readme page

> I've decided to switch to using only this, I find using this in a browser is just perfect and way better than bloated softwares from printer manufacturers

I won't attribute it to you specifically. I assume you won't mind since it's public on here anyway, but let me know if you'd prefer I didn't.

**Comment by toxic0berliner** [comment]
Go ahead, I stand by what I said ;)

**Pull request merged**
