### PR TITLE
Arabic translation

### PR DESCRIPTION
**Pull request by yoursred**
The interface would now need a RTL mode, that unfortunately is beyond my capabilities.

### CODE REVIEW

**Comment by yoursred** [comment]
I have it running on RPI3, RTL support is the only thing missing.

**Comment by sbs20** [comment]
Awesome! Thank you. I'll try and get RTL sorted soon.

**Comment by sbs20** [comment]
Screenshot 2022-12-30 at 15 55 33

RTL seems to swap EVERYTHING over. Is that acceptable? I'm afraid I'm quite ignorant when it comes to this kind of thing.

**Comment by yoursred** [comment]
Yup, that is how it's supposed to work.

**Comment by sbs20** [comment]
> Yup, that is how it's supposed to work.

Brilliant! Thanks so much for your help!

**Pull request merged**
